name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [ '6.x', '7.x', '8.x' ]
        include:
          - os: ubuntu-latest
            dotnet-version: '6.x'
            target-framework: 'netstandard2.0'
          - os: ubuntu-latest
            dotnet-version: '7.x'
            target-framework: 'netstandard2.0'
          - os: ubuntu-latest
            dotnet-version: '8.x'
            target-framework: 'netstandard2.0'
          - os: windows-latest
            dotnet-version: '6.x'
            target-framework: 'net48'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore --framework ${{ matrix.target-framework }}

      - name: Run unit tests
        run: dotnet test tests --no-build --verbosity normal