name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]
    outputs:
      tag_name: ${{ steps.set_output_tag_name.outputs.tag_name }}
      display_version: ${{ steps.set_output_display_version.outputs.display_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Exclude WebApiSample.Framework48 from solution
        run: dotnet sln remove samples/WebApiSample.Framework48/WebApiSample.Framework48.csproj

      - name: Exclude WebApiSample from solution
        run: dotnet sln remove samples/WebApiSample/WebApiSample.csproj

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set output tag name
        id: set_output_tag_name
        run: echo "tag_name=${{ env.TAG_NAME }}" >> $GITHUB_OUTPUT

      - name: Extract display version
        id: extract_display_version
        run: echo "DISPLAY_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set output display version
        id: set_output_display_version
        run: echo "display_version=${{ env.DISPLAY_VERSION }}" >> $GITHUB_OUTPUT

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:VersionPrefix=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher
        run: dotnet pack ./src/FlexFetcher/FlexFetcher.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher.DependencyInjection.Microsoft
        run: dotnet pack ./src/FlexFetcher.DependencyInjection.Microsoft/FlexFetcher.DependencyInjection.Microsoft.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher.Serialization.NewtonsoftJson
        run: dotnet pack ./src/FlexFetcher.Serialization.NewtonsoftJson/FlexFetcher.Serialization.NewtonsoftJson.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher.Serialization.SystemTextJson
        run: dotnet pack ./src/FlexFetcher.Serialization.SystemTextJson/FlexFetcher.Serialization.SystemTextJson.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      #- name: Publish to NuGet
      #  run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set prerelease variable
        id: set_prerelease
        run: |
          if [[ "${GITHUB_REF}" == *"-"* ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Set TAG_NAME
        run: echo "TAG_NAME=${{ needs.build.outputs.tag_name }}" >> $GITHUB_ENV

      - name: Set DISPLAY_VERSION
        run: echo "DISPLAY_VERSION=${{ needs.build.outputs.display_version }}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DISPLAY_VERSION }}
          name: ${{ env.DISPLAY_VERSION }}
          draft: true
          prerelease: ${{ env.PRERELEASE }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nupkgs/*.nupkg
          asset_name: $(basename ./artifacts/*.nupkg)
          asset_content_type: application/zip