name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Exclude WebApiSample.Framework48 from solution
        run: dotnet sln remove samples/WebApiSample.Framework48/WebApiSample.Framework48.csproj

      - name: Exclude WebApiSample from solution
        run: dotnet sln remove samples/WebApiSample/WebApiSample.csproj

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Extract display version
        id: extract_display_version
        run: echo "DISPLAY_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:VersionPrefix=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher
        run: dotnet pack ./src/FlexFetcher/FlexFetcher.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher.DependencyInjection.Microsoft
        run: dotnet pack ./src/FlexFetcher.DependencyInjection.Microsoft/FlexFetcher.DependencyInjection.Microsoft.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher.Serialization.NewtonsoftJson
        run: dotnet pack ./src/FlexFetcher.Serialization.NewtonsoftJson/FlexFetcher.Serialization.NewtonsoftJson.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Pack FlexFetcher.Serialization.SystemTextJson
        run: dotnet pack ./src/FlexFetcher.Serialization.SystemTextJson/FlexFetcher.Serialization.SystemTextJson.csproj --no-build -o ./nupkgs -p:PackageVersion=${{ env.TAG_NAME }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Set prerelease variable
        id: set_prerelease
        run: |
          if [[ "${GITHUB_REF}" == *"-"* ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DISPLAY_VERSION }}
          name: ${{ env.DISPLAY_VERSION }}
          draft: true
          prerelease: ${{ env.PRERELEASE }}
          files: |
            ./nupkgs/FlexFetcher.${{ env.TAG_NAME }}.nupkg
            ./nupkgs/FlexFetcher.DependencyInjection.Microsoft.${{ env.TAG_NAME }}.nupkg
            ./nupkgs/FlexFetcher.Serialization.NewtonsoftJson.${{ env.TAG_NAME }}.nupkg
            ./nupkgs/FlexFetcher.Serialization.SystemTextJson.${{ env.TAG_NAME }}.nupkg